import {test} from "node:test";
import assert from "node:assert/strict";
import {RemoteError} from "../cloudflare.mjs";
import {fixture} from "./fixture.mjs";

test("publishing with analytics wires the project, records the tag and exposes the dashboard link",async t=>{
 const f=fixture(t),s=f.service;
 const op=await s.prepare({artifactId:"a1",version:1,analytics:true});await f.confirm(op);
 assert.equal(s.op(op.id).status,"published");
 const p=s.pub(op.publication_id);
 assert.ok(p.analytics_tag);
 assert.equal(f.projects.get(p.project).build_config.web_analytics_tag,p.analytics_tag);
 assert.equal(f.projects.get(p.project).build_config.web_analytics_token,"token1");
 assert.equal(f.rumSites.get(p.project+".pages.dev").site_tag,p.analytics_tag);
 const st=await s.state(),card=st.publications[0];
 assert.match(card.analytics.url,new RegExp("web-analytics/overview\\?siteTag~in="+p.analytics_tag));
});
test("an explicit update preserves analytics and an explicit off clears it",async t=>{
 const f=fixture(t),s=f.service;
 const op=await s.prepare({artifactId:"a1",version:1,analytics:true});await f.confirm(op);
 const p=s.pub(op.publication_id),patched=f.calls.filter(c=>c==="analytics-patch").length;
 await f.confirm(await s.prepare({artifactId:"a1",version:2}));
 assert.equal(s.pub(p.id).analytics_tag,p.analytics_tag);
 assert.equal(f.calls.filter(c=>c==="analytics-patch").length,patched);
 await f.confirm(await s.prepare({artifactId:"a1",version:2,analytics:false}));
 assert.equal(s.pub(p.id).analytics_tag,null);
 assert.equal(f.projects.get(p.project).build_config.web_analytics_tag,null);
 assert.equal(f.calls.filter(c=>c==="analytics-patch").length,patched+1);
});
test("the analytics toggle is a confirmed site-only change and is idempotent",async t=>{
 const f=fixture(t),s=f.service;
 const op=await s.prepare({artifactId:"a1",version:1});await f.confirm(op);
 const p=s.pub(op.publication_id);
 const change=await s.prepare({action:"analytics",publicationId:p.id,analytics:true});
 assert.match(change.confirmation.message,/next publication/);
 assert.equal(change.analytics,1);
 const deploys=f.calls.filter(c=>c==="deploy").length;
 await f.confirm(change);
 assert.ok(s.pub(p.id).analytics_tag);
 assert.equal(f.projects.get(p.project).build_config.web_analytics_tag,s.pub(p.id).analytics_tag);
 assert.equal(f.calls.filter(c=>c==="deploy").length,deploys);
 const again=await s.prepare({action:"analytics",publicationId:p.id,analytics:true});
 assert.equal(again.unchanged,true);
 const off=await s.prepare({action:"analytics",publicationId:p.id,analytics:false});
 assert.match(off.confirmation.message,/stop reporting/);
 await f.confirm(off);
 assert.equal(s.pub(p.id).analytics_tag,null);
 const offAgain=await s.prepare({action:"analytics",publicationId:p.id,analytics:false});
 assert.equal(offAgain.unchanged,true);
});
test("a foreign analytics configuration is refused, never overwritten",async t=>{
 const f=fixture(t),s=f.service;
 const op=await s.prepare({artifactId:"a1",version:1});await f.confirm(op);
 const p=s.pub(op.publication_id);
 f.projects.get(p.project).build_config={web_analytics_tag:"foreign",web_analytics_token:"foreign-token"};
 const change=await s.prepare({action:"analytics",publicationId:p.id,analytics:true});
 await f.confirm(change);
 assert.equal(s.op(change.id).status,"failed");
 assert.match(s.op(change.id).error,/outside this extension/);
 assert.equal(f.projects.get(p.project).build_config.web_analytics_tag,"foreign");
 assert.equal(s.pub(p.id).analytics_tag,null);
});
test("a lost analytics create response is adopted by hostname, never created twice",async t=>{
 const f=fixture(t),s=f.service,orig=f.remote.createRumSite;
 f.remote.createRumSite=async host=>{const site=await orig(host);throw new RemoteError("response lost");};
 const op=await s.prepare({artifactId:"a1",version:1,analytics:true});await f.confirm(op);
 assert.equal(s.op(op.id).status,"published");
 assert.equal(f.calls.filter(c=>c==="rum-create").length,1);
 const p=s.pub(op.publication_id);
 assert.equal(f.projects.get(p.project).build_config.web_analytics_tag,p.analytics_tag);
});
test("removal deletes the analytics site; a lost delete holds without repeating",async t=>{
 const f=fixture(t),op=await f.service.prepare({artifactId:"a1",version:1,analytics:true});await f.confirm(op);
 const p=f.service.pub(op.publication_id),tag=p.analytics_tag,orig=f.remote.deleteRumSite;
 let lost=true;
 f.remote.deleteRumSite=async t2=>{await orig(t2);if(lost){lost=false;throw new RemoteError("response lost");}};
 const remove=await f.service.prepare({action:"remove",publicationId:p.id});await f.confirm(remove);
 assert.equal(f.service.op(remove.id).status,"unknown");
 assert.equal(f.projects.size,0);
 f.service.reconcile(remove.id);await f.settle();
 assert.equal(f.service.op(remove.id).status,"removed");
 assert.equal(f.calls.filter(c=>c==="rum-delete").length,2);
 assert.equal(f.service.pub(p.id).analytics_tag,null);
 assert.equal([...f.rumSites.values()].some(s=>s.site_tag===tag),false);
});
test("a failing analytics cleanup keeps removal open until the site is gone",async t=>{
 const f=fixture(t),op=await f.service.prepare({artifactId:"a1",version:1,analytics:true});await f.confirm(op);
 const p=f.service.pub(op.publication_id);
 f.remote.deleteRumSite=async()=>{throw new RemoteError("Cloudflare refused the request (HTTP 500).");};
 const remove=await f.service.prepare({action:"remove",publicationId:p.id});await f.confirm(remove);
 assert.equal(f.service.op(remove.id).status,"unknown");
 f.service.reconcile(remove.id);await f.settle();
 assert.equal(f.service.op(remove.id).status,"unknown");
 assert.equal(f.service.pub(p.id).status,"published");
 assert.equal(f.rumSites.size,1);
 f.remote.deleteRumSite=async tag=>{f.rumSites.delete(p.project+".pages.dev");};
 f.service.reconcile(remove.id);await f.settle();
 assert.equal(f.service.op(remove.id).status,"removed");
 assert.equal(f.service.pub(p.id).analytics_tag,null);
});
test("upload progress is tracked per file and exposed in state",async t=>{
 const f=fixture(t),s=f.service;
 f.bundles.get(1).files=[{path:"a.html"},{path:"b.html"},{path:"c.html"}];
 const orig=f.remote.deploy;
 f.remote.deploy=async(name,bundle,marker,onProgress)=>{for(let i=0;i<3;i++)onProgress();return orig(name,bundle,marker,onProgress);};
 const op=await s.prepare({artifactId:"a1",version:1,analytics:true});await f.confirm(op);
 assert.equal(s.op(op.id).status,"published");
 const row=(await s.state()).publications[0].operations.find(o=>o.id===op.id);
 assert.deepEqual(row.progress,{uploaded:3,total:3});
});
