import {test} from "node:test";
import assert from "node:assert/strict";
import {DatabaseSync} from "node:sqlite";
import {readFileSync,readdirSync} from "node:fs";
import {PagesService} from "../service.mjs";
import {Cloudflare,RemoteError} from "../cloudflare.mjs";
function fixture(t){const db=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).sort())db.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));t.after(()=>db.close());let values={},secrets={},calls=0,fail=false;const service=new PagesService({db,host:async()=>({values,secrets}),remote:()=>({checkConnection:async()=>{calls++;if(fail)throw new RemoteError('Cloudflare refused the token.',403)}})});return {service,set:(a,token)=>{values={account_id:a};secrets={api_token:token}},fail:()=>fail=true,calls:()=>calls};}
test('missing, saved, verified, rotated and rejected credentials remain distinct without leaking secrets',async t=>{const f=fixture(t),s=f.service;assert.deepEqual(await s.connectionState(),{status:'not-configured'});await assert.rejects(s.checkConnection(),/Configure/);assert.equal(f.calls(),0);f.set('a'.repeat(32),'sensitive-token');assert.equal((await s.connectionState()).status,'unchecked');assert.equal((await s.checkConnection()).status,'ready');assert.equal(f.calls(),1);assert.ok(!JSON.stringify(await s.connectionState()).includes('sensitive-token'));assert.ok(!JSON.stringify(await s.connectionState()).includes('fingerprint'));f.set('a'.repeat(32),'rotated-token');assert.equal((await s.connectionState()).status,'unchecked');f.fail();const rejected=await s.checkConnection();assert.equal(rejected.status,'error');assert.equal(rejected.retryable,false);assert.equal(f.calls(),2);assert.equal(s.db.prepare('SELECT count(*) n FROM publications').get().n,0)});
test('account check makes one HTTPS read with redirects refused, not a remote mutation',async()=>{let request;const cf=new Cloudflare('a'.repeat(32),'secret',async(url,opts)=>{request={url,...opts};return {ok:true,json:async()=>({success:true,result:[]})}});await cf.checkConnection();assert.equal(request.url,'https://api.cloudflare.com/client/v4/accounts/'+'a'.repeat(32)+'/pages/projects?per_page=1');assert.equal(request.method,'GET');assert.equal(request.redirect,'error');assert.equal(request.body,undefined)});
test('provider permission rejection is sanitized and an invalid response is refused',async()=>{const cf=new Cloudflare('a'.repeat(32),'secret',async()=>({ok:false,status:403,json:async()=>({success:false,errors:[{message:'echo-secret'}]})}));await assert.rejects(cf.checkConnection(),e=>e.status===403&&!e.message.includes('echo-secret'));const invalid=new Cloudflare('a'.repeat(32),'secret',async()=>({ok:true,json:async()=>({success:true,result:{}})}));await assert.rejects(invalid.checkConnection(),/project list/)});
test('a check finishing after settings change cannot certify the new credentials',async t=>{const f=fixture(t);f.set('a'.repeat(32),'old-token');let release;f.service.remote=()=>({checkConnection:()=>new Promise(r=>release=r)});const pending=f.service.checkConnection();await new Promise(r=>setTimeout(r,0));f.set('b'.repeat(32),'new-token');release();assert.equal((await pending).status,'unchecked');assert.equal((await f.service.connectionState()).status,'unchecked')});
